---
title: "Samuel Raduenz"
format: html
editor: visual
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(WDI)

options(scipen = 999) # REMOVER A NOT. CIENT.
# DADOS EM PAINEL
dadospib <- WDI(country = 'all', 
                indicator = 'NY.GDP.MKTP.CD')

paises <- c('BR', 'US')

dadospibbrus <- WDI(country = paises, 
                    indicator = 'NY.GDP.MKTP.CD')

# CORTE TRANSVERSAL
dadospib2023 <- WDI(country = 'all', 
                    indicator = 'NY.GDP.MKTP.CD',
                    start = 2023, end = 2023)

# SÉRIE TEMPORAL
dadospibbr <- WDI(country = 'BR', 
                  indicator = 'NY.GDP.MKTP.CD')

```

## VARIÁVEL

Falar sobre a varável escolhida. Qual a fonte? Qual a medida?

## GRÁFICO DE DADOS EM PAINEL

Falar sobre o gráfico de dados em painel

```{r}
#| label: dadospib
#| warning: false
#| echo: false

ggplot(dadospib,  
       mapping = aes(y= NY.GDP.MKTP.CD, x = year)) +
  geom_point()

```

## TRANSVERSASL

Falar sobre gráficos corte transversal

```{r}
#| label: dadospib2023  
#| warning: false 
#| echo: false  

ggplot(dadospib2023, 
       mapping = aes(y = NY.GDP.MKTP.CD, 
                     x = year)) +
  geom_point() 
```

## SÉRIE TEMPORAL

Falar sobre gráficos de série temporal

```{r}
#| label: dadospibbr  
#| warning: false  
#| echo: false    

ggplot(dadospibbr,
                    mapping = aes(y = NY.GDP.MKTP.CD,
                                  x = year)) +
  geom_line(color = "blue") +
  labs(
    title = "Dados Pib do Brasil",
    x = "Ano",
    y = "Pib em Dólares")
```
